import random
english_words= [
    {"mot": "Authentication", "definition": "Processus de vérification de l’identité d’un utilisateur ou d’un système."},
    {"mot": "Bit", "definition": "Unité binaire de base de l’information, 0 ou 1."},
    {"mot": "Bluetooth", "definition": "Technologie de communication sans fil à courte portée."},
    {"mot": "Browser Extension", "definition": "Petit logiciel ajoutant des fonctionnalités au navigateur web."},
    {"mot": "Cache Hit", "definition": "Situation où les données demandées sont trouvées dans le cache."},
    {"mot": "Cloud Computing", "definition": "Utilisation de ressources informatiques via Internet."},
    {"mot": "Container", "definition": "Environnement léger pour exécuter des applications de manière isolée."},
    {"mot": "Cryptocurrency", "definition": "Monnaie numérique sécurisée par cryptographie."},
    {"mot": "Data Warehouse", "definition": "Base de données centralisée pour l’analyse de grandes quantités de données."},
    {"mot": "Debugger", "definition": "Outil utilisé pour analyser et corriger un programme."},
    {"mot": "Deep Learning", "definition": "Technique d’apprentissage automatique basée sur des réseaux neuronaux profonds."},
    {"mot": "DevOps", "definition": "Pratiques combinant développement logiciel et opérations informatiques."},
    {"mot": "DNS", "definition": "Système de noms de domaine qui traduit les noms en adresses IP."},
    {"mot": "Docker", "definition": "Plateforme pour créer, déployer et gérer des conteneurs."},
    {"mot": "Ethernet", "definition": "Technologie de réseau local câblé."},
    {"mot": "Frontend", "definition": "Partie visible d’une application ou d’un site web avec laquelle l’utilisateur interagit."},
    {"mot": "Git", "definition": "Système de gestion de versions décentralisé."},
    {"mot": "Hash", "definition": "Fonction transformant des données en une valeur fixe, utilisée pour sécuriser ou indexer."},
    {"mot": "Hotspot", "definition": "Point d’accès Wi-Fi permettant la connexion à Internet."},
    {"mot": "HTML5", "definition": "Dernière version du langage HTML avec plus de fonctionnalités multimédias."},
    {"mot": "IoT", "definition": "Internet des objets, réseau d’appareils connectés communiquant entre eux."},
    {"mot": "IPsec", "definition": "Suite de protocoles pour sécuriser les communications IP."},
    {"mot": "Javascript Framework", "definition": "Bibliothèque facilitant le développement avec JavaScript (ex: React, Angular)."},
    {"mot": "Kernel Panic", "definition": "Erreur critique du système d’exploitation provoquant son arrêt."},
    {"mot": "Latency", "definition": "Délai entre une action et sa réponse dans un système."},
    {"mot": "Load Balancer", "definition": "Dispositif répartissant la charge entre plusieurs serveurs."},
    {"mot": "Machine Learning", "definition": "Technique où les ordinateurs apprennent à partir de données."},
    {"mot": "Microservices", "definition": "Architecture logicielle composée de services indépendants et modulaires."},
    {"mot": "Multithreading", "definition": "Exécution simultanée de plusieurs threads dans un programme."},
    {"mot": "Node.js", "definition": "Environnement d’exécution JavaScript côté serveur."},
    {"mot": "OAuth", "definition": "Protocole d’autorisation permettant l’accès sécurisé à des ressources."},
    {"mot": "Payload", "definition": "Partie utile d’un paquet de données envoyée sur un réseau."},
    {"mot": "Phishing", "definition": "Technique d’hameçonnage pour obtenir des informations sensibles."},
    {"mot": "Python", "definition": "Langage de programmation interprété, polyvalent et populaire."},
    {"mot": "Query", "definition": "Requête envoyée à une base de données pour récupérer des données."},
    {"mot": "React", "definition": "Bibliothèque JavaScript pour construire des interfaces utilisateur."},
    {"mot": "Regression Testing", "definition": "Tests visant à vérifier qu’une modification n’a pas introduit de bugs."},
    {"mot": "Router", "definition": "Appareil dirigeant les paquets de données dans un réseau informatique."},
    {"mot": "SaaS", "definition": "Logiciel en tant que service accessible via Internet."},
    {"mot": "Scrum", "definition": "Méthode agile de gestion de projet informatique."},
    {"mot": "SDK", "definition": "Ensemble d’outils pour développer des applications sur une plateforme donnée."},
    {"mot": "SQL", "definition": "Langage pour interroger et manipuler des bases de données relationnelles."},
    {"mot": "Token", "definition": "Jeton utilisé pour authentifier et sécuriser les sessions."},
    {"mot": "UI", "definition": "Interface utilisateur."},
    {"mot": "UX", "definition": "Expérience utilisateur, l’ensemble des perceptions et réactions de l’utilisateur."},
    {"mot": "Virtual Machine", "definition": "Environnement logiciel simulant un ordinateur complet."},
    {"mot": "Webhook", "definition": "Mécanisme permettant à une application d’envoyer des notifications en temps réel."},
    {"mot": "Zero-day", "definition": "Vulnérabilité inconnue des développeurs et exploitée par des attaquants."}
  ]


proverbFrancais = [
  "Prends le temps d’écouter avant de parler.",
  "Ne remets pas à demain ce que tu peux faire aujourd’hui.",
  "Apprends à pardonner pour avancer.",
  "Sois toujours fidèle à toi-même.",
  "La simplicité est la clé du bonheur.",
  "Garde ton calme en toute circonstance.",
  "Ne crains pas l’échec, c’est un pas vers le succès.",
  "Choisis bien tes amis, ils influencent ta vie.",
  "Écoute plus que tu ne parles.",
  "Le respect se gagne, ne se commande pas.",
  "Sois patient, tout vient à point à qui sait attendre.",
  "Ne juge pas avant de comprendre.",
  "Le silence est parfois la meilleure réponse.",
  "Cultive la gratitude chaque jour.",
  "N’aie pas peur de changer d’avis.",
  "Travaille dur en silence, laisse le succès faire du bruit.",
  "N’attends pas que les choses arrivent, fais-les arriver.",
  "Prends soin de ta santé, elle est ton vrai trésor.",
  "Sois généreux sans attendre de retour.",
  "Vis le moment présent sans anxiété.",
  "Ne te compare pas aux autres, sois ta meilleure version.",
  "Apprends de tes erreurs, elles sont tes maîtres.",
  "Rêve grand, commence petit.",
  "Sois humble dans la victoire comme dans la défaite.",
  "Apprends à dire non quand il le faut.",
  "Ne laisse pas la colère gouverner tes actions.",
  "Fais confiance à ton instinct.",
  "Aide les autres sans attendre de récompense.",
  "Sois responsable de tes choix.",
  "Le bonheur se construit jour après jour.",
  "Prends du temps pour toi, tu le mérites.",
  "Évite les mauvaises fréquentations.",
  "La vraie richesse est intérieure.",
  "N’aie pas honte de demander de l’aide.",
  "Apprends à te relever après une chute.",
  "La vie est un apprentissage constant.",
  "Ne cherche pas la perfection, cherche l’équilibre.",
  "Le succès commence par une bonne organisation.",
  "Sois fidèle à tes valeurs.",
  "Ne gaspille pas ton énergie dans la rancune.",
  "Cultive la bienveillance envers toi-même et les autres.",
  "Sois ouvert aux critiques constructives.",
  "Prends le temps de te reposer et de réfléchir.",
  "L’honnêteté est la meilleure politique.",
  "Ne te décourage pas face aux obstacles.",
  "Le changement commence par une décision.",
  "Valorise les petites victoires.",
  "Apprends à écouter ton cœur.",
  "Sois constant dans tes efforts.",
  "Le vrai courage, c’est d’être soi-même.",
  "Après la pluie, le beau temps.",
  "L’espoir fait vivre.",
  "Chaque jour est une nouvelle chance.",
  "Le sourire est la clé du cœur.",
  "La patience est la mère de la réussite.",
  "Rien ne sert de courir, il faut partir à point.",
  "Qui veut, peut.",
  "L’union fait la force.",
  "Aide-toi, le ciel t’aidera.",
  "Il n’y a pas de mal sans bien.",
  "Chaque chose en son temps.",
  "Les petits ruisseaux font les grandes rivières.",
  "Mieux vaut prévenir que guérir.",
  "La vie est un défi, relève-le !",
  "Il faut savoir tourner la page.",
  "Qui ne risque rien n’a rien.",
  "Le bonheur est dans les petites choses.",
  "La force vient de l’intérieur.",
  "L’amour triomphe de tout.",
  "La générosité enrichit celui qui donne.",
  "Ce qui ne te tue pas te rend plus fort.",
  "On apprend de ses erreurs.",
  "La confiance est le début de toute réussite.",
  "Le courage ouvre toutes les portes.",
  "Un sourire coûte moins cher que l’électricité.",
  "La liberté commence où l’ignorance finit.",
  "Le travail paie toujours.",
  "Le respect attire le respect.",
  "La vérité finit toujours par triompher.",
  "La gratitude transforme ce que nous avons en suffisance.",
  "Rêve grand, commence petit.",
  "Chaque fin est un nouveau départ.",
  "La sagesse vient avec l’expérience.",
  "La paix commence avec un sourire.",
  "Le temps guérit toutes les blessures.",
  "Un jour à la fois.",
  "La bienveillance est une langue universelle.",
  "Le succès est la somme de petits efforts répétés.",
  "Il faut savoir donner sans attendre.",
  "L’espoir est la lumière dans l’obscurité.",
  "L’humilité est la clé du savoir.",
  "La persévérance mène à la réussite.",
  "Le respect de soi est le début du respect des autres.",
  "La joie partagée est une double joie.",
  "Chaque jour est un cadeau.",
  "Cultive la paix en toi.",
  "L’énergie positive attire le positif.",
  "La confiance en soi est le premier secret du succès.",
  "Le sourire est le début de l’amitié."
]

proverbArabe = [
     "استمع قبل أن تتكلم.",
  "لا تؤجل عمل اليوم إلى الغد.",
  "تعلّم كيف تغفر لتتقدم في حياتك.",
  "كن صادقاً مع نفسك دائماً.",
  "البساطة مفتاح السعادة.",
  "حافظ على هدوئك في كل الظروف.",
  "لا تخف من الفشل فهو خطوة نحو النجاح.",
  "اختر أصدقائك بعناية، فهم يؤثرون على حياتك.",
  "استمع أكثر مما تتحدث.",
  "الاحترام يُكتسب ولا يُفرض.",
  "الصبر مفتاح الفرج.",
  "لا تحكم قبل أن تفهم.",
  "الصمت أحياناً أفضل جواب.",
  "ازرع الامتنان في قلبك يومياً.",
  "لا تخف من تغيير رأيك.",
  "اعمل بجد بصمت، ودع النجاح يتكلم.",
  "لا تنتظر الأشياء تحدث، بل اجعلها تحدث.",
  "اهتم بصحتك فهي كنزك الحقيقي.",
  "كن كريماً دون انتظار مقابل.",
  "عش الحاضر بدون قلق.",
  "لا تقارن نفسك بالآخرين، كن أفضل نسخة منك.",
  "تعلم من أخطائك فهي معلمك.",
  "احلم كبيراً وابدأ صغيراً.",
  "كن متواضعاً في النصر والهزيمة.",
  "تعلم قول لا حين يلزم.",
  "لا تدع الغضب يحكم تصرفاتك.",
  "ثق بحدسك.",
  "ساعد الآخرين دون انتظار مكافأة.",
  "كن مسؤولاً عن اختياراتك.",
  "السعادة تُبنى يوماً بعد يوم.",
  "خذ وقتاً لنفسك، أنت تستحق ذلك.",
  "تجنب الصحبة السيئة.",
  "الثروة الحقيقية داخلية.",
  "لا تخجل من طلب المساعدة.",
  "تعلم كيف تنهض بعد السقوط.",
  "الحياة تعلم مستمر.",
  "لا تسعَ للكمال، بل للاتزان.",
  "النجاح يبدأ بتنظيم جيد.",
  "كن مخلصاً لقيمك.",
  "لا تضيع طاقتك في الحقد.",
  "ازرع اللطف في نفسك وفي الآخرين.",
  "كن منفتحاً على النقد البناء.",
  "خذ وقتاً للراحة والتفكير.",
  "الصدق أفضل سياسة.",
  "لا تيأس أمام العقبات.",
  "التغيير يبدأ بقرار.",
  "قدّر الانتصارات الصغيرة.",
  "تعلم أن تستمع لقلبك.",
  "كن مثابراً في جهودك.",
  "الشجاعة الحقيقية أن تكون نفسك.",
  "بعد العسر يسرا.",
  "الأمل يصنع المعجزات.",
  "من جد وجد.",
  "القناعة كنز لا يفنى.",
  "الصبر مفتاح الفرج.",
  "من توكل على الله فهو حسبه.",
  "العقل زينة.",
  "التفاؤل نصف الحياة.",
  "لا يأس مع الحياة.",
  "الإرادة تصنع المستحيل.",
  "العطاء بلا حدود.",
  "الصدق منجاة.",
  "الابتسامة صدقة.",
  "التجربة أم الحكمة.",
  "النجاح يبدأ بخطوة.",
  "المحبة أساس السلام.",
  "القوة في الوحدة.",
  "العمل عبادة.",
  "كل شيء بوقته حلو.",
  "الزهر لا يذبل في القلب.",
  "الحكمة ضالة المؤمن.",
  "الأمل نور القلب.",
  "لا شيء مستحيل مع الإرادة.",
  "الصداقة أغلى من الذهب.",
  "النية الطيبة طريق النجاح.",
  "العقل والجهد طريق النجاح.",
  "النجاح تاج على رؤوس الطموحين.",
  "التسامح يفتح الأبواب المغلقة.",
  "الوقت كالسيف إن لم تقطعه قطعك.",
  "العطاء يضاعف البركة.",
  "الحياة فرصة فاغتنمها.",
  "التفكير الإيجابي يجلب النجاح.",
  "المثابرة طريق النجاح.",
  "العقل يحكم القلب.",
  "القلب الكبير لا يعرف الحقد.",
  "العطاء سر السعادة.",
  "الأمل يبني المستقبل.",
  "لا تقل لا أستطيع.",
  "الكرم صفة العظماء.",
  "السعادة في القناعة.",
  "العلم نور والجهل ظلام.",
  "النجاح يأتي بالصبر والعمل.",
  "التواضع طريق العظمة.",
  "الإيمان يصنع المعجزات.",
  "القلوب الطيبة لا تعرف الحقد.",
  "الصبر مفتاح النجاح.",
  "الحكمة ضالة الإنسان.",
  "الأمل بداية كل شيء.",
  "التعاون يصنع القوة."
]

activites_maman_fille = [
    "Peindre des dessins avec des aquarelles",
    "Créer des bijoux en perles",
    "Faire un pique-nique dans le salon",
    "Fabriquer des marionnettes en chaussettes",
    "Préparer des cupcakes et les décorer",
    "Faire un collage avec des photos et magazines",
    "Construire un fort avec des coussins et couvertures",
    "Jouer à cache-cache",
    "Faire du jardinage et planter des fleurs",
    "Lire des livres ensemble",
    "Créer un carnet de souvenirs",
    "Jouer à des jeux de société",
    "Organiser une chasse au trésor",
    "Faire des expériences scientifiques simples",
    "Apprendre à faire du tricot ou crochet",
    "Regarder un film et faire du pop-corn maison",
    "Fabriquer des cartes de vœux personnalisées",
    "Faire des origamis faciles",
    "Danser sur de la musique préférée",
    "Faire des dessins géants à la craie dehors",
    "Créer des bougies parfumées maison",
    "Décorer des galets ou cailloux",
    "Apprendre quelques mots dans une langue étrangère",
    "Jouer au théâtre ou inventer des histoires",
    "Faire un gâteau ensemble",
    "Organiser un défilé de mode avec ses vêtements",
    "Faire des bulles de savon dans le jardin",
    "Fabriquer un herbier avec des feuilles et fleurs",
    "Jouer aux devinettes",
    "Construire des puzzles ensemble",
    "Créer un album photo ou scrapbook",
    "Faire un tableau de vision avec des images découpées",
    "Jouer à imiter des animaux",
    "Faire du yoga ou des étirements ensemble",
    "Créer des bijoux en pâte à sel",
    "Faire un dessin à quatre mains",
    "Apprendre à faire des noeuds et bracelets en corde",
    "Organiser un goûter pour ses poupées",
    "Faire des décorations pour sa chambre",
    "Observer les étoiles la nuit",
    "Faire des coloriages en grand format",
    "Jouer à des jeux éducatifs en ligne",
    "Fabriquer un mobile pour sa chambre",
    "Faire un théâtre de marionnettes",
    "Jouer au bowling avec des bouteilles en plastique",
    "Faire des pâtés de sable (ou pâte à modeler)",
    "Écouter des histoires audio ensemble",
    "Inventer une chanson ou une danse",
    "Faire une séance photo rigolote"
]


def get_random_words(n=5):
    return random.sample(english_words, n)

def get_random_proverbs():
    return random.choice(proverbFrancais), random.choice(proverbArabe)

def get_random_activity():
    return random.choice(activites_maman_fille)